base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path('', views.button_action, name='button_action'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("accounts.urls")),
    path("posts/", include("posts.urls")),
    path("profiles/", include("profiles.urls")),
    path("users/", include("users.urls")),
    path("follows/", include("follows.urls")),
    path("settings/", include("settings.urls")),
]\
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include
from . import views

app_name = "posts"

urlpatterns = [
    path("create/", views.CreateView.as_view(), name="create"),
    path("index/", views.IndexView.as_view(), name="index"),
    path("", views.ListView.as_view(), name="list"),
    path("profiles/", include("profiles.urls")),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"

urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("my/", views.DetailLoginUserView.as_view(), name="detail_login_user"),
    path("my/update/", views.UpdateLoginUserView.as_view(), name="update_login_user"),
    path("my/color-mode/", ColorModeUpdateView.as_view(), name="color_mode_update"),
]

base/views.py
from datetime import timedelta
from django.shortcuts import redirect

def button_action(request):
    # クッキーが設定されていない場合
    if request.COOKIES.get('colorMode') is None:
        # 最初にページに訪れたときはクッキーを設定してリダイレクト
        color_mode = 'light'
        response = redirect('accounts:home')  # 現在のページにリダイレクト
        response.set_cookie('colorMode', color_mode, max_age=timedelta(days=30), secure=True, httponly=True)  # クッキー設定
        return response
    else:
        # クッキーが設定されている場合、現在のモードを反転させる
        current_mode = request.COOKIES.get('colorMode')
        color_mode = 'light' if current_mode == 'dark' else 'dark'
        
        # モードを反転させて、リダイレクトなしでクッキーを更新
        response = redirect('accounts:home')  # 現在のページにリダイレクト
        response.set_cookie('colorMode', color_mode, max_age=timedelta(days=30), secure=True, httponly=True)  # 新しいモードに更新
        return response

templates/base.html
{% load static %}
<!doctype html>
<html lang="ja" data-bs-theme="{{color_mode}}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>

  <body>
    <div class="container">
      <div class="row">
          <div class="col"></div>

          <!-- メインコンテンツエリア -->
          <!-- Medium以上で6/12カラム, その他で10/12カラム -->
          <div class="col-10 col-md-6">
            {% block content %}{% endblock %}
          </div>

        <div class="col"></div>
      </div>
    </div>

    <!-- ナビゲーションバー -->
    <nav class="navbar navbar-expand-sm fixed-top bg-body">
      <div class="container justify-content-evenly">

        <a class="navbar-brand" href="{% url 'accounts:home' %}">
          <i class="bi bi-house-door-fill"></i>
          <!-- Medium以上で表示 -->
          <span class="d-none d-md-inline">Home</span>
        </a>

        <a class="navbar-brand" href="#">
          <i class="bi bi-search"></i>
          <span class="d-none d-md-inline">Search</span>
        </a>

        <a class="navbar-brand" href="{% url 'posts:create' %}">
          <i class="bi bi-plus-circle-fill"></i>
          <span class="d-none d-md-inline">New Post</span>
        </a>

        <a class="navbar-brand" href="{% url 'profiles:detail_login_user' %}">
          <i class="bi bi-person-circle"></i>
          <span class="d-none d-md-inline">Profile</span>
        </a>

      </div>
    </nav>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>