base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path('', views.button_action, name='button_action'),
]

follows/urls.py
from django.urls import path
from . import views

app_name = "follows"

urlpatterns = [
    path("add/<int:user>/", views.FollowView.add, name="add"),
    path("remove/<int:user>/", views.FollowView.remove, name="remove"),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
]

posts/urls.py
from django.urls import path, include
from . import views

app_name = "posts"

urlpatterns = [
    path("create/", views.CreateView.as_view(), name="create"),
    path("index/", views.IndexView.as_view(), name="index"),
    path("", views.ListView.as_view(), name="list"),
    path("profiles/", include("profiles.urls")),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("<slug:login_id>/", views.DetailView.as_view(), name="detail"),
    path("<slug:login_id>/followList", views.FollowListView.as_view(), name="followList"),
    path("<slug:login_id>/followerList", views.FollowerListView.as_view(), name="followerList"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from profiles.models import Profile

class User(AbstractUser):
  class Meta:
    db_table = 'users'

  # AbstractUser から継承される username を削除
  username = None

  login_id = models.CharField(max_length=20, unique=True)

  nickname = models.CharField(max_length=100)

  USERNAME_FIELD = 'login_id'
  REQUIRED_FIELDS = ['nickname']

  follow_user_set = models.ManyToManyField(
    'self',
    db_table='follows',
    symmetrical=False,
    related_name='follower_user_set'
  )

  profile_picture = models.ImageField(upload_to='profile_pictures/', default='default_profile.png')
  
  bio = models.TextField(blank=True, default="")
  
  following = models.ManyToManyField('self', symmetrical=False, related_name='followers')


  def save(self, *args, **kwargs):
    # https://docs.djangoproject.com/ja/5.0/ref/models/instances/#state
    adding = self._state.adding
    # 下記の実装でも同様
    #adding = not self._state.db
    #adding = self.pk is None

    super().save(args, kwargs)

    # save() でINSERTされる場合であっても
    # save() 後に `_state.adding` を参照すると False になる
    #print(f'adding after save: {self._state.adding}')

    # INSERTされる場合のみ Profile も create する
    if adding:
      Profile.objects.create(user=self)

home/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    nickname = models.CharField(max_length=30, unique=True)

    def get_following_users(self):
        """ フォローしているユーザーの一覧を取得 """
        return User.objects.filter(followers__follower=self)
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]  # 投稿を降順に

posts/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
  class Meta:
    db_table = 'posts'

  user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
  content = models.CharField('投稿内容', max_length=255)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.content

users/models.py
# from django.contrib.auth.models import AbstractUser
# from django.db import models

# class User(AbstractUser):
#     profile_picture = models.ImageField(upload_to='profile_pictures/', default='default_profile.png')
#     bio = models.TextField(blank=True, default="")
#     following = models.ManyToManyField('self', symmetrical=False, related_name='followers')

posts/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):

  class Meta:
    model = Post
    fields = ('content', )
    widgets = {
      'content': forms.Textarea(),
    }

users/forms.py
from django import forms
from django.forms import widgets,ModelForm

from accounts.models import User
from posts.models import Post
from profiles.models import Profile

class UsersHomeForm(ModelForm):
  class Meta:
    model = User, Post, Profile
    fields = ('User.nickname','User.login_id',)
    widget = {
      'nickname': forms.Textarea(),
      'login_id': forms.Textarea(),
    }

  # nickname = widgets.CharField(attrs={'class': 'nickname'})
  # login_id = widgets.CharField(attrs={'class': 'login_id'})

  def __init__(self, *args, **kargs):
    super().__init__(*args, **kargs)
    for UsersHomeInform in self.fields.values():
      UsersHomeInform.widget.attrs["class"] = "UsersHomeInform"

follows/views.py
from django.shortcuts import redirect
from django.views.generic import RedirectView
from django.shortcuts import get_object_or_404

class addView(RedirectView):
    pattern_name = "users:detail"

    # フォロー機能
    def follow_view(self, *args, **kwargs):
        to_user = get_object_or_404(User, pk=kwargs["user_id"]);
        follow_user = self.request.user
        request.follow_user_set.add(follow_user)
        return redirect('users:detail', login_id=follow_user.login_id)
        
class removeView(RedirectView):
    pattern_name = "users:detail"

    # フォロー解除
    def unfollow_view(self, *args, **kwargs):
        to_user = get_object_or_404(User, pk=kwargs["user_id"]);
        from_user = self.request.user
        request.follow_user_set.remove(follow_user)
        return redirect('users:detail', login_id=follow_user.login_id)

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from posts.models import Post

# Create your views here.
class IndexView(TemplateView):
  template_name = "home/index.html"

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)

    # フォローユーザのポスト, 投稿降順
    # SELECT posts.id, ... users.id, ..., profiles.id
    #   <= N+1問題回避のため select_related() で user, profile も取得
    # FROM posts INNER JOIN users ... INNER JOIN follows ... LEFT OUTER JOIN profiles ...
    #   <= filter() で指定した post -> user -> follow_user_set(follows 経由の user) がINNER JOINされている
    #   <= profiles は select_related() しているだけのため外部結合(LEFT OUTER JOIN)にしてくれている模様
    # WHERE follows.from_user_id = [ログインユーザのid]
    # ORDER BY posts.created_at DESC
    post_list = Post.objects\
      .filter(user__follower_user_set__pk=self.request.user.pk)\
      .select_related("user__profile")\
      .order_by("-created_at")

    context['post_list'] = post_list

    return context

posts/views.py
from django.views.generic import CreateView, ListView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy
from . import forms
from .models import Post


# Create your views here.
class CreateView(CreateView):
  form_class = forms.PostForm
  template_name = "posts/create.html"
  success_url = reverse_lazy("posts:list")

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)


class IndexView(TemplateView):
  template_name = "posts/list.html"

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    post_list = Post.objects.all()
    context["post_list"] = post_list
    return context


class ListView(ListView):
  template_name = "posts/list.html"

  """ (1) ListView のクラス変数 model を指定するケース
  model = Post

  # contextに格納される名前は "object_list" もしくは "[モデル名]_list" となる。
  # templateからは以下のどちらでもアクセスできる。
  # - object_list
  # - post_list
  # これら以外の名前でtemplateからアクセスしたい場合は任意の名前で格納する必要がある。
  # context_object_name = 'hoge_list'
  """

  """ (2) ListView のクラス変数 queryset を指定するケース
  # クラス変数のため静的な指定のみ。
  # 動的な指定(例: リクエスト内容に応じた絞込み)をしたい場合は
  # get_queryset() のオーバーライドを用いる必要がある。
  queryset = Post.objects.all()
  """

  """ (3) ListView のメソッド get_queryset() をオーバーライドするケース """
  model = Post

  def get_queryset(self):
    queryset = super().get_queryset()
    # ログインユーザの post の降順
    queryset = queryset.filter(user=self.request.user).order_by("id").reverse()
    return queryset

users/views.py
from django.views.generic.detail import DetailView as GenericDetailView
from accounts.models import User

class DetailView(GenericDetailView):
    model = User
    template_name = "users/detail.html"
    slug_url_kwarg = "login_id"
    slug_field = "login_id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object

        context['profile_image'] = user.profile.image.url

        # Userに紐づくPostのリスト
        post_list = user.post_set.all().order_by('-id')
        context['post_list'] = post_list

        # フォローしているか否か
        followed = self.request.user.follow_user_set.filter(id=user.id).exists()
        context['followed'] = followed

        context['follows_count'] = user.follow_user_set.count()
        context['followers_count'] = user.follower_user_set.count()

        return context


class FollowsView(GenericDetailView):
    model = User
    template_name = "users/follows.html"
    slug_url_kwarg = "login_id"
    slug_field = "login_id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # URL中の login_id に紐づくUserインスタンス
        # (Detailviewの実装によって既に取得されている)
        user = self.object
        context['profile_image'] = user.profile.image.url

        # TODO 登録降順(follows.id desc)でソートしたいところだが
        # ManyToManyField で through を使用しておらず中間Modelがないことが影響してか
        # 対処のしようがない？
        follow_user_set = user.follow_user_set.select_related("profile").all()
        context['follow_user_set'] = follow_user_set

        return context


class FollowersView(GenericDetailView):
    model = User
    template_name = "users/followers.html"
    slug_url_kwarg = "login_id"
    slug_field = "login_id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # URL中の login_id に紐づくUserインスタンス
        # (Detailviewの実装によって既に取得されている)
        user = self.object
        context['profile_image'] = user.profile.image.url

        # TODO 登録降順(follows.id desc)でソートしたいところだが
        # ManyToManyField で through を使用しておらず中間Modelがないことが影響してか
        # 対処のしようがない？
        follower_user_set = user.follower_user_set.select_related("profile").all()
        context['follower_user_set'] = follower_user_set

        return context

templates/users/dashboard.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
  <div>
    <h1>
      {{ user.nickname }}
    </h1>
    <div class="text-muted">
      @{{ user.login_id }}
    </div>
    <div class="mt-2 mb-2">
      {{ user.profile.self_introduction | linebreaksbr }}
    </div>
  </div>
  <div class="mt-2 mb-2">
    <div class="col-xl">
      {% for post in post_list %}
      <div class="card rounded-0 px-3">
        <div class="row">
          <div class="col-1 pt-2">
            <i class="bi bi-person-circle"></i>
          </div>
          <div class="col-11">
            <div class="row justify-content-start">
              <div class="col-auto p-1 fs-5">
                {{ user.nickname }}
              </div>
              <div class="col-auto align-self-center px-1 pt-1 text-muted">
                @{{ user.login_id }}
              </div>
              <div class="col-auto align-self-center px-1 pt-1 text-muted">
                {{ post.created_at }}
              </div>
            </div>
            <div class="row p-1">
              {{ post.content | linebreaksbr }}
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/users/detail.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}{{ user.nickname }} (@{{ user.login_id }}) さん{% endblock %}

{% block content %}
<div class="container">
    <div class="text-end">
        {% if user != request.user %}
            {% if followed %}
                <form action="{% url 'follows:remove' user_id=user.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-primary">フォロー中</button>
                </form>
            {% else %}
                <form action="{% url 'follows:add' user_id=user.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">フォロー</button>
                </form>
            {% endif %}
        {% endif %}
    </div>

    <div class="w-25">
        {% include "profiles/partials/image.html" %}
    </div>

    <h1>
        {{ user.nickname  }}
    </h1>
    <p>
        <span class="opacity-50">@{{ user.login_id }}</span>
    </p>
    <p>
        {{ user.profile.self_introduction|linebreaksbr }}
    </p>

    <div>
        <a href="{% url 'users:follows' login_id=user.login_id %}"
        class="text-reset link-underline-dark link-underline-opacity-0 link-underline-opacity-75-hover">
            <span class="fw-bolder">{{ follows_count | intcomma }}</span> フォロー中
        </a>

        <span class="ms-3"></span>

        <a href="{% url 'users:followers' login_id=user.login_id %}"
        class="text-reset link-underline-dark link-underline-opacity-0 link-underline-opacity-75-hover">
            <span class="fw-bolder">{{ followers_count | intcomma }}</span> フォロワー
        </a>
    </div>

    <div class="m-3"></div>

    <div>
        {% for post in post_list %}
            {% include "posts/partials/post.html" %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/follow_list.html
{% extends "base.html" %}
{% block title %}フォロー中{% endblock %}

{% block content %}
<div class="container">
    <h1>
        {{ profile_user.nickname  }}
    </h1>
    <p>
        <span class="opacity-50">@{{ profile_user.login_id }}</span>
    </p>
    <div>
        {% for follow in follow_list %}
            <div class="row border p-1">
                <div class="col-1">
                    <i class="bi bi-person-circle"></i>
                </div>
                <div class="col">
                    <div class="row fw-bolder">
                        {{ follow.nickname }}
                    </div>
                    <div class="row opacity-50">
                        @{{ follow.login_id }}
                    </div>
                    <div class="row">
                        {{ follow.profile.self_introduction|linebreaksbr }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/followerList.html
{% extends "base.html" %}
{% block title %}フォローワー一覧{% endblock %}
{% block content %}

<div class="container">
    <h1>
        {{ user.nickname }}
    </h1>
    <p class="text-black-50">@{{ user.login_id }}</p>

    <h2 class="fw-bolder">フォロー中</h2>
    <div>
        {% for user in follower_list %}
            {% include "users/partials/user.html" %}
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/users/follower_list.html
{% extends "base.html" %}
{% block title %}フォロワー{% endblock %}

{% block content %}
<div class="container">
    <h1>
        {{ profile_user.nickname  }}
    </h1>
    <p>
        <span class="opacity-50">@{{ profile_user.login_id }}</span>
    </p>
    <div>
        {% for follower in follower_list %}
            <div class="row border p-1">
                <div class="col-1">
                    <i class="bi bi-person-circle"></i>
                </div>
                <div class="col">
                    <div class="row fw-bolder">
                        {{ follower.nickname }}
                    </div>
                    <div class="row opacity-50">
                        @{{ follower.login_id }}
                    </div>
                    <div class="row">
                        {{ follower.profile.self_introduction|linebreaksbr }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/followers.html
{% extends "base.html" %}
{% block title %}{{ user.nickname }} (@{{ user.login_id }}) さんをフォローしているアカウント{% endblock %}

{% block content %}
<div class="container">
    <div class="w-25">
        {% include "profiles/partials/image.html" %}
    </div>

    <h1>
        {{ user.nickname  }}
    </h1>
    <p>
        <span class="opacity-50">@{{ user.login_id }}</span>
    </p>

    <h2>フォロワー</h2>

    <div class="m-3"></div>

    <div>
        {% for follower_user in follower_user_set %}
            {% include "users/partials/user.html" with user=follower_user %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/following.html
{% extends "base.html" %}
{% block title %}フォロー一覧{% endblock %}

{% block content %}
<div class="container">
    <h2><p>{{ following }}</p>フォロー中</h2>
    <div>
        {% for user in follows %}
            {% include "users/partials/user.html" %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/follows.html
{% extends "base.html" %}
{% block title %}{{ user.nickname }} (@{{ user.login_id }}) さんがフォローしているアカウント{% endblock %}

{% block content %}
<div class="container">
    <div class="w-25">
        {% include "profiles/partials/image.html" %}
    </div>

    <h1>
        {{ user.nickname  }}
    </h1>
    <p>
        <span class="opacity-50">@{{ user.login_id }}</span>
    </p>

    <h2>フォロー中</h2>

    <div class="m-3"></div>

    <div>
        {% for follow_user in follow_user_set %}
            {% include "users/partials/user.html" with user=follow_user %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/foloowing.html
{% extends "base.html" %}
{% block title %}フォロー一覧{% endblock %}

{% block content %}
<div class="container">
    <p>{{ following }}</p>
    <h2>フォロー中</h2>
    <div>
        {% for user in follows %}
            {% include "users/partials/user.html" %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/home.html
{% extends "base.html" %}
{% block title %}ホーム{% endblock %}

{% block content %}
<div class="container">
  <h2>{{ user.nickname }}</h2>
  <p class="text-black-50">@{{ user.login_id }}</p>
  <div class="text-wrap">
    {{ user.profile.self_introduction }}
  </div>
  <div class="mt-2">
    {% for post in post_list %}
      {% include "posts/partials/post.html" with post=post %}
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/users/posts.html
{% extends "base.html" %}
{% block title %}ユーザ詳細{% endblock %}

{% block content %}
<div class="container">
    <h1>
        {{ user.nickname  }}
    </h1>
    <p>
        <span class="opacity-50">@{{ user.login_id }}</span>
    </p>
    <p>
        {{ user.profile.self_introduction|linebreaksbr }}
    </p>

    <div>
        {% for post in post_list %}
            {% include "posts/partials/post.html" %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/user.html
{% extends "base.html" %}
{% block title %}ユーザー詳細{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-5">{{ user.nickname }}</h1>
    <div class="text-muted my-3">@{{ user.login_id }}</div>
    <div>{{ user.profile.self_introduction | linebreaksbr }}</div>
    <div class="my-5">
        {% for post in posts %}
            {% include 'posts/partials/post.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/user_detail.html
{% extends "base.html" %}
{% block title %}ポスト一覧{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ object.nickname }}</h1>
    <p class="text-secondary">@{{ object.login_id }}</p>
    <p>{{ profile.self_introduction  | linebreaksbr }}</p>
    <div class="conatiner">
        {% for post in post_list %}
        <div class="continer">
            <div class="row">
                <div class = "col-sm-1">
                    <i class="bi bi-person-circle"></i>
                </div>
                <div class="col">
                    <div class = "row">
                        <div class="col p-0">
                            {{ object.nickname }}
                        </div>
                        <div class="col p-0　">
                            <p class="text-secondary">
                            @
                            {{ object.login_id }}
                            {{ post.created_at }}
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class ="col"">
                            {{ post.content | linebreaksbr}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/user_home.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}ユーザーのホーム画面{% endblock %}

{% block content %}
<div class="user-id mt-3">
    <div class="user-profile row">
        <div class="col-12">
            <h1>{{ profile.nickname }}</h1>
            <p>Login ID: {{ user.username }}</p>
            <p>Introduction: {{ profile.self_introduction }}</p>
        </div>
    </div>
    <div class="posts mt-4 row">
        <h2 class="col-12">Posts</h2>
        {% for post in posts %}
            <div class="post card my-3 col-12">
                <div class="card-body">
                    <h5 class="post-title d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            {% if post.user.profile.icon %}
                                <img src="{{ post.user.profile.icon.url }}" alt="User Icon" class="rounded-circle" width="40" height="40">
                            {% endif %}
                            <span class="ms-2">{{ post.user.profile.nickname }} ({{ post.user.userid }})</span>
                        </div>
                        <small class="text-muted">{{ post.created_at|date:"Y年n月j日 H:i" }}</small>
                    </h5>
                    <p class="card-text">{{ post.content }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}